# SPDX-FileCopyrightText: The Open Annihilation Authors; see COPYRIGHT
# SPDX-License-Identifier: GPL-3.0-only

cmake_minimum_required(VERSION 3.24)
project(oa_ui_frontend_state LANGUAGES CXX)
include(CTest)
add_library(oa-ui-frontend-state src/dispatcher.cpp src/app_modes.cpp src/main_menu.cpp src/game_entry.cpp src/initialization.cpp src/skirmish_ui.cpp src/map_selection.cpp)
add_library(oa::ui::frontend_state ALIAS oa-ui-frontend-state)
target_include_directories(oa-ui-frontend-state PUBLIC include)
target_compile_features(oa-ui-frontend-state PUBLIC cxx_std_20)
if(TARGET oa-options)
  target_link_libraries(oa-ui-frontend-state PUBLIC oa-options)
endif()
target_link_libraries(oa-ui-frontend-state PUBLIC oa-core-types oa-data-match-rules PRIVATE oa-data-campaign oa-data-map-pack)
if(BUILD_TESTING)
  add_executable(oa-frontend-state-test tests/dispatcher_test.cpp)
  target_link_libraries(oa-frontend-state-test PRIVATE oa-ui-frontend-state)
  add_test(NAME frontend-state-dispatcher COMMAND oa-frontend-state-test)
  add_executable(oa-map-selection-test tests/map_selection_test.cpp)
  target_link_libraries(oa-map-selection-test PRIVATE oa-ui-frontend-state)
  add_test(NAME frontend-map-selection COMMAND oa-map-selection-test)
  add_executable(oa-skirmish-ui-test tests/skirmish_ui_test.cpp)
  target_link_libraries(oa-skirmish-ui-test PRIVATE oa-ui-frontend-state)
  add_test(NAME frontend-skirmish-ui COMMAND oa-skirmish-ui-test)
  add_executable(oa-frontend-initialization-test tests/initialization_test.cpp)
  target_link_libraries(oa-frontend-initialization-test PRIVATE oa-ui-frontend-state)
  add_test(NAME frontend-initialization COMMAND oa-frontend-initialization-test)
  add_executable(oa-game-entry-test tests/game_entry_test.cpp)
  target_link_libraries(oa-game-entry-test PRIVATE oa-ui-frontend-state)
  add_test(NAME frontend-game-entry COMMAND oa-game-entry-test)
  add_executable(oa-main-menu-test tests/main_menu_test.cpp)
  target_link_libraries(oa-main-menu-test PRIVATE oa-ui-frontend-state)
  add_test(NAME frontend-main-menu COMMAND oa-main-menu-test)
endif()

if(BUILD_TESTING)
  add_executable(oa-frontend-alliance-members-test tests/alliance_members_test.cpp)
  target_link_libraries(oa-frontend-alliance-members-test PRIVATE oa-ui-frontend-state)
  add_test(NAME frontend-alliance-members COMMAND oa-frontend-alliance-members-test)
endif()
